name: Alejandro Bisquertt Blog
favicon: null
layout_spectrum: 0.48274
typography_spectrum: 0.49854
title: 'Ideas sobre emprendimiento, biología y tecnología '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e7e7e7'
    - '#00aa9d'
    - '#cdcdcd'
    - '#30b7ad'
    - '#808080'
  brandStrength: 0.375
  lightness: 0.3145733217243105
  saturation: 0.6875
  rhythmicContrast: 0.05486881849355996
purpose: []
