name: Alejandro Bisquertt Blog
favicon: null
layout_spectrum: 0.48274
typography_spectrum: 0.49854
title: 'Ideas sobre emprendimiento, Biologia y Tecnologia '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7c95bb'
    - '#090e14'
    - '#a2b2cb'
    - '#2d4160'
    - '#e8e8e8'
  brandStrength: 0.8605857405345887
  lightness: 0.3145733217243105
  saturation: 0.7524240966886282
  rhythmicContrast: 0.05486881849355996
purpose: []
